### ISSUE TITLE
Add/configure UFW

### ISSUE THREAD

**Issue by perguth** [perguth/chromeos-developer-setup#1]
Firewall should be added and be set up in order to protect against incoming traffic for Yggdrasil.

**Comment by perguth** [comment]
Already in it. xD

**Comment by perguth** [comment]
Maybe that breaks the Terminal:

```

  - block: # UFW Firewall
    - name: '[UFW] Allow SSH'
      ufw:
        rule: allow
        port: '22'
        proto: tcp
    - name: '[UFW] Allow MOSH'
      ufw:
        rule: allow
        port: 60000:61000
        proto: udp
    - name: '[UFW] Allow HTTPS'
      ufw:
        rule: allow
        port: '443'
        proto: tcp
    - name: '[UFW] Allow Yggdrasil traffic'
      ufw:
        rule: allow
        direction: in
        interface: tun0
    - name: '[UFW] Default deny incoming'
      ufw:
        rule: deny
        direction: in
    - name: '[UFW] Enable'
      ufw:
        state: enabled
```
